// https://www.swiggy.com/dapi/restaurants/list/v5?lat=22.5645175&lng=72.928871&page_type=DESKTOP_WEB_LISTING
export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const restaurantsData = {
  cards: [
    {
      cardType: "seeAllRestaurants",
      layoutAlignmentType: "VERTICAL",
      data: {
        type: "seeAllRestaurants",
        data: {
          title: "SEE ALL",
          totalOpenRestaurants: 149,
          cards: [
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "695577",
                name: "William John's Pizza Superlative",
                uuid: "8722d959-b771-45e0-a2f5-4bb798b399c7",
                city: "93",
                area: "mahadev-nagar",
                totalRatingsString: "Too Few Ratings",
                cloudinaryImageId: "ccc221d10f63c124af22a5f719e12131",
                cuisines: ["Pizzas", "Fast Food", "Beverages"],
                tags: [],
                costForTwo: 30000,
                costForTwoString: "₹300 FOR TWO",
                deliveryTime: 20,
                minDeliveryTime: 20,
                maxDeliveryTime: 20,
                slaString: "20 MINS",
                lastMileTravel: 2.4000000953674316,
                slugs: {
                  restaurant:
                    "william-johns-pizza-superlative-mahadev-nagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "101, Krishna Saffron, Near APC, V V Nagar  Road, Anand, Anand , Anand , Gujarat-388001",
                locality: "V v Nagar Road",
                parentId: 306659,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                ribbon: [],
                chain: [],
                feeDetails: {},
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID:
                  "cid=6831466~p=1~eid=00000188-3dd3-4829-6435-982800d40165",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "2.4 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "₹125 OFF",
                  subHeader: "ABOVE ₹199",
                  discountTag: "FLAT DEAL",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "695577",
                  deliveryTime: 20,
                  minDeliveryTime: 20,
                  maxDeliveryTime: 20,
                  lastMileTravel: 2.4000000953674316,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: true,
                avgRating: "--",
                totalRatings: 0,
                new: true,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "588510",
                name: "La Milano Pizzeria",
                uuid: "c7607763-6e53-4035-84d4-74371127645f",
                city: "93",
                area: "F1 Radha keshav complex",
                totalRatingsString: "500+ ratings",
                cloudinaryImageId: "p1serixl9sdprq47nump",
                cuisines: ["Pizzas"],
                tags: [],
                costForTwo: 40000,
                costForTwoString: "₹400 FOR TWO",
                deliveryTime: 22,
                minDeliveryTime: 22,
                maxDeliveryTime: 22,
                slaString: "22 MINS",
                lastMileTravel: 2.200000047683716,
                slugs: {
                  restaurant: "la-milano-pizzeria-mahadev-nagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "F1, radha keshav complex, Opp. Home science college, Mota bazar, vallabh vidyanagar 388120",
                locality: "Vallabh Vidyanagar",
                parentId: 22533,
                unserviceable: false,
                veg: false,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "2.2 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "60% OFF",
                  subHeader: "UPTO ₹120",
                  discountTag: "",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "588510",
                  deliveryTime: 22,
                  minDeliveryTime: 22,
                  maxDeliveryTime: 22,
                  lastMileTravel: 2.200000047683716,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "3.9",
                totalRatings: 500,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "145386",
                name: "Kapildev Fast food ",
                uuid: "b9e9095f-f641-41ac-bb1c-a0861548b6d8",
                city: "93",
                area: "Vidhyanagar",
                totalRatingsString: "500+ ratings",
                cloudinaryImageId: "osm8mfzcopxevkq4yad7",
                cuisines: ["Pizzas"],
                tags: [],
                costForTwo: 20000,
                costForTwoString: "₹200 FOR TWO",
                deliveryTime: 23,
                minDeliveryTime: 23,
                maxDeliveryTime: 23,
                slaString: "23 MINS",
                lastMileTravel: 1.399999976158142,
                slugs: {
                  restaurant: "kapildev-fast-food-vidhyanagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "Near Mahivas, Bakrol Road, Vallabh Vidhyanagar - 388120",
                locality: "Bakrol Road",
                parentId: 114860,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "1.3 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "10% OFF",
                  subHeader: "UPTO ₹40",
                  discountTag: "",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "145386",
                  deliveryTime: 23,
                  minDeliveryTime: 23,
                  maxDeliveryTime: 23,
                  lastMileTravel: 1.399999976158142,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "3.9",
                totalRatings: 500,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "323897",
                name: "Nini's Kitchen",
                uuid: "9b80ee5c-a510-4cad-89bb-1f57b08b9e63",
                city: "93",
                area: "Vallabh Vidyanagar",
                totalRatingsString: "100+ ratings",
                cloudinaryImageId: "b2a784c6aab862d229bd76494abeb16a",
                cuisines: [
                  "Indian",
                  "Pizzas",
                  "Chinese",
                  "Lebanese",
                  "Beverages",
                ],
                tags: [],
                costForTwo: 100000,
                costForTwoString: "₹1000 FOR TWO",
                deliveryTime: 22,
                minDeliveryTime: 22,
                maxDeliveryTime: 22,
                slaString: "22 MINS",
                lastMileTravel: 2.5999999046325684,
                slugs: {
                  restaurant: "nini's-kitchen-mahadev-nagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "C/O. Kinal K Patel, Plot No:533/534, Vidhyanagar Railway  Station Road, Vidhyanagar, Anand. 388120",
                locality: "Mahadev Nagar",
                parentId: 11105,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                ribbon: [
                  {
                    type: "PROMOTED",
                  },
                ],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID:
                  "cid=6810700~p=4~eid=00000188-3dd3-4829-6435-982900d40469",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "2.5 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "10% OFF",
                  subHeader: "UPTO ₹40",
                  discountTag: "",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "323897",
                  deliveryTime: 22,
                  minDeliveryTime: 22,
                  maxDeliveryTime: 22,
                  lastMileTravel: 2.5999999046325684,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: true,
                avgRating: "4.4",
                totalRatings: 100,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "245015",
                name: "Taste Of Bombay Sandwich",
                uuid: "f753d705-e2ab-4403-b1bd-72ebfbd580fb",
                city: "93",
                area: "Vallabh Vidyanagar",
                totalRatingsString: "100+ ratings",
                cloudinaryImageId: "xxwdoasvjddbpamxzsfg",
                cuisines: ["Fast Food", "Beverages"],
                tags: [],
                costForTwo: 15000,
                costForTwoString: "₹150 FOR TWO",
                deliveryTime: 17,
                minDeliveryTime: 17,
                maxDeliveryTime: 17,
                slaString: "17 MINS",
                lastMileTravel: 1.2999999523162842,
                slugs: {
                  restaurant: "taste-of-bombay-sandwich-bakrol-bakrol",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "G-1,SHANKAR HEIGHTS,NR.RAGHUVIR CHOKDI VIDYANAGAR,ANAND",
                locality: "Raghuvir Chokdi ",
                parentId: 201540,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "1.2 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "20% OFF",
                  subHeader: "UPTO ₹100",
                  discountTag: "",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "245015",
                  deliveryTime: 17,
                  minDeliveryTime: 17,
                  maxDeliveryTime: 17,
                  lastMileTravel: 1.2999999523162842,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "4.1",
                totalRatings: 100,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "146937",
                name: "Maji Sainik Omlet Centre",
                uuid: "6e5711e7-44f3-4415-8b79-5dbf82f96425",
                city: "93",
                area: "Vallabh Vidyanagar",
                totalRatingsString: "1000+ ratings",
                cloudinaryImageId: "nuypapp03tmjk0tb5snf",
                cuisines: ["Fast Food", "Biryani"],
                tags: [],
                costForTwo: 20000,
                costForTwoString: "₹200 FOR TWO",
                deliveryTime: 21,
                minDeliveryTime: 21,
                maxDeliveryTime: 21,
                slaString: "21 MINS",
                lastMileTravel: 1.2000000476837158,
                slugs: {
                  restaurant:
                    "maji-sainik-omlet-centre-v-v-nagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address: "G F 14 Ground Floor, R C complex, V V Nagar - 388120",
                locality: "Mahadev Nagar",
                parentId: 130477,
                unserviceable: false,
                veg: false,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "1.2 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "50% OFF",
                  subHeader: "UPTO ₹100",
                  discountTag: "",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "146937",
                  deliveryTime: 21,
                  minDeliveryTime: 21,
                  maxDeliveryTime: 21,
                  lastMileTravel: 1.2000000476837158,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "4.1",
                totalRatings: 1000,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "367846",
                name: "Vadilal Scoop Shop",
                uuid: "f78716af-45e1-4461-aa2c-32723d8eb521",
                city: "93",
                area: "Karamsad",
                totalRatingsString: "100+ ratings",
                cloudinaryImageId: "htl0ponqhye7ywupzbzr",
                cuisines: ["Ice Cream"],
                tags: [],
                costForTwo: 30000,
                costForTwoString: "₹300 FOR TWO",
                deliveryTime: 18,
                minDeliveryTime: 18,
                maxDeliveryTime: 18,
                slaString: "18 MINS",
                lastMileTravel: 3,
                slugs: {
                  restaurant: "vadilal-scoop-shop-mahadev-nagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "GF SHOP NO. 10, RAMDEV RESIDENCY, NEAR GANGABA CHHATRALAY, V.V ROAD, KARAMSAD, DIST - ANAND 388001",
                locality: "Mahadev Nagar",
                parentId: 11750,
                unserviceable: false,
                veg: false,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                ribbon: [
                  {
                    type: "PROMOTED",
                  },
                ],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID:
                  "cid=6789253~p=7~eid=00000188-3dd3-4829-6435-982a00d4075c",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "3 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "₹125 OFF",
                  subHeader: "ABOVE ₹249",
                  discountTag: "FLAT DEAL",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "367846",
                  deliveryTime: 18,
                  minDeliveryTime: 18,
                  maxDeliveryTime: 18,
                  lastMileTravel: 3,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: true,
                avgRating: "4.5",
                totalRatings: 100,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "672266",
                name: "Anandi Nasta House",
                uuid: "9f9fc4aa-dbf3-445e-aba1-b3b7adf245e1",
                city: "93",
                area: "mahadev-nagar",
                totalRatingsString: "Too Few Ratings",
                cloudinaryImageId: "ee4131fd2ba063b8fe1b815586d1fe83",
                cuisines: ["Indian", "Snacks", "Beverages"],
                tags: [],
                costForTwo: 15000,
                costForTwoString: "₹150 FOR TWO",
                deliveryTime: 19,
                minDeliveryTime: 19,
                maxDeliveryTime: 19,
                slaString: "19 MINS",
                lastMileTravel: 1.2000000476837158,
                slugs: {
                  restaurant: "anandi-nasta-house-mahadev-nagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "KAILASHBEN R TALSANIYA/201 SAHAJ AVENUE,OPP. GAYATRI DINING HALL,NANA BAZAR,VALLABH VIDHYANAGAR ,Vallabh Vidyanagar ,Anand ,Anand ,Gujarat-388120",
                locality: "Nana Bazar",
                parentId: 402682,
                unserviceable: false,
                veg: false,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "1.2 kms",
                hasSurge: false,
                sla: {
                  restaurantId: "672266",
                  deliveryTime: 19,
                  minDeliveryTime: 19,
                  maxDeliveryTime: 19,
                  lastMileTravel: 1.2000000476837158,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "--",
                totalRatings: 0,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "262753",
                name: "Yo Frankie",
                uuid: "f8f6e1dd-a1df-46dc-ae03-2cadf0112849",
                city: "93",
                area: "Vallabh Vidyanagar",
                totalRatingsString: "100+ ratings",
                cloudinaryImageId: "oxemks8dzm9sukuaahll",
                cuisines: ["Beverages"],
                tags: [],
                costForTwo: 15000,
                costForTwoString: "₹150 FOR TWO",
                deliveryTime: 22,
                minDeliveryTime: 22,
                maxDeliveryTime: 22,
                slaString: "22 MINS",
                lastMileTravel: 2.299999952316284,
                slugs: {
                  restaurant: "yo-frankie-mahadev-nagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "Center, H M Patel Trade, Pappaji Marg, Mota Bazaar, Vallabh Vidyanagar, Anand, Gujarat 388120",
                locality: "Mahadev Nagar",
                parentId: 5990,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "2.2 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "50% OFF",
                  subHeader: "UPTO ₹100",
                  discountTag: "",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "262753",
                  deliveryTime: 22,
                  minDeliveryTime: 22,
                  maxDeliveryTime: 22,
                  lastMileTravel: 2.299999952316284,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "4.1",
                totalRatings: 100,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "603118",
                name: "Barbeque Nation",
                uuid: "b0a3edb3-1ab0-4d85-9357-6467edaf0049",
                city: "93",
                area: "Jitodia",
                totalRatingsString: "100+ ratings",
                cloudinaryImageId: "rcnp03tpleyvjkmqwi4b",
                cuisines: [
                  "North Indian",
                  "Barbecue",
                  "Biryani",
                  "Kebabs",
                  "Mughlai",
                  "Desserts",
                ],
                tags: [],
                costForTwo: 60000,
                costForTwoString: "₹600 FOR TWO",
                deliveryTime: 28,
                minDeliveryTime: 28,
                maxDeliveryTime: 28,
                slaString: "28 MINS",
                lastMileTravel: 4.699999809265137,
                slugs: {
                  restaurant: "barbeque-nation-anand-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "Barbeque Nation, 203 To 210, 2nd Floor, Maruti Solaris Mall, Anand-Sojitra Road, Anand, Gujarat-388001.",
                locality: "Maruti Solaris Mall",
                parentId: 2438,
                unserviceable: false,
                veg: false,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                ribbon: [
                  {
                    type: "PROMOTED",
                  },
                ],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 1900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 1900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "1900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID:
                  "cid=6818476~p=10~eid=00000188-3dd3-4829-6435-982b00d40a35",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "4.6 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "₹125 OFF",
                  subHeader: "ABOVE ₹249",
                  discountTag: "FLAT DEAL",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "603118",
                  deliveryTime: 28,
                  minDeliveryTime: 28,
                  maxDeliveryTime: 28,
                  lastMileTravel: 4.699999809265137,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: true,
                avgRating: "3.9",
                totalRatings: 100,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "175104",
                name: "Tasty Vadapav And Frenkie",
                uuid: "20e57e1d-f092-4938-b546-7a491a0af6ac",
                city: "93",
                area: "Vallabh Vidyanagar",
                totalRatingsString: "500+ ratings",
                cloudinaryImageId: "ylpcvh3scn8yis9aomq7",
                cuisines: ["Fast Food"],
                tags: [],
                costForTwo: 10000,
                costForTwoString: "₹100 FOR TWO",
                deliveryTime: 19,
                minDeliveryTime: 19,
                maxDeliveryTime: 19,
                slaString: "19 MINS",
                lastMileTravel: 2.5,
                slugs: {
                  restaurant:
                    "tasty-vadapav-and-frenkie-vallabh-vidyanagar-vidya-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "G 2, Rama plaza Complex, Oppo Home science College, Mota Bazar, Vallabh Vidyanagar, 389120",
                locality: "Rama plaza Complex",
                parentId: 202222,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "2.5 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "10% OFF",
                  subHeader: "UPTO ₹40",
                  discountTag: "",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "175104",
                  deliveryTime: 19,
                  minDeliveryTime: 19,
                  maxDeliveryTime: 19,
                  lastMileTravel: 2.5,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "4.3",
                totalRatings: 500,
                new: false,
              },
              subtype: "basic",
            },
            {
              type: "restaurant",
              data: {
                type: "F",
                id: "260350",
                name: "Kabir Restaurant",
                uuid: "1979455d-3130-4ee7-80c9-4afc02e846a5",
                city: "93",
                area: "Vallabh Vidyanagar",
                totalRatingsString: "1000+ ratings",
                cloudinaryImageId: "qdl0jmzjs4gak6oeryri",
                cuisines: ["Chinese", "North Indian", "Ice Cream", "Biryani"],
                tags: [],
                costForTwo: 25000,
                costForTwoString: "₹250 FOR TWO",
                deliveryTime: 16,
                minDeliveryTime: 16,
                maxDeliveryTime: 16,
                slaString: "16 MINS",
                lastMileTravel: 2.200000047683716,
                slugs: {
                  restaurant: "kabir-restaurant-mahadev-nagar-mahadev-nagar",
                  city: "anand",
                },
                cityState: "93",
                address:
                  "Mota Bazaar, Vallabh Vidyanagar, Anand, Gujarat 388120",
                locality: "Mahadev Nagar",
                parentId: 7631,
                unserviceable: false,
                veg: true,
                select: false,
                favorite: false,
                tradeCampaignHeaders: [],
                chain: [],
                feeDetails: {
                  fees: [
                    {
                      name: "distance",
                      fee: 900,
                      message: "",
                    },
                    {
                      name: "time",
                      fee: 0,
                      message: "",
                    },
                    {
                      name: "special",
                      fee: 0,
                      message: "",
                    },
                  ],
                  totalFees: 900,
                  message: "",
                  title: "Delivery Charge",
                  amount: "900",
                  icon: "",
                },
                availability: {
                  opened: true,
                  nextOpenMessage: "",
                  nextCloseMessage: "",
                },
                longDistanceEnabled: 0,
                rainMode: "NONE",
                thirdPartyAddress: false,
                thirdPartyVendor: "",
                adTrackingID: "",
                badges: {
                  imageBased: [],
                  textBased: [],
                  textExtendedBadges: [],
                },
                lastMileTravelString: "2.2 kms",
                hasSurge: false,
                aggregatedDiscountInfoV3: {
                  header: "₹125 OFF",
                  subHeader: "ABOVE ₹199",
                  discountTag: "FLAT DEAL",
                  headerTypeV2: 0,
                },
                sla: {
                  restaurantId: "260350",
                  deliveryTime: 16,
                  minDeliveryTime: 16,
                  maxDeliveryTime: 16,
                  lastMileTravel: 2.200000047683716,
                  lastMileDistance: 0,
                  serviceability: "SERVICEABLE",
                  rainMode: "NONE",
                  longDistance: "NOT_LONG_DISTANCE",
                  preferentialService: false,
                  iconType: "EMPTY",
                },
                promoted: false,
                avgRating: "4.1",
                totalRatings: 1000,
                new: false,
              },
              subtype: "basic",
            },
          ],
        },
      },
    },
  ],
};
